### ISSUE TITLE
Reasoning behind FastICA/PCA vectors for GMM

### ISSUE THREAD

**Issue by njanakiev** [pbaylies/clustering-laion400m#1]
Just out of curiosity, I was wondering what the reasoning was behind using a combined PCA and FastICA vectors for Gaussian Mixture Models. I wasn't able to find this kind of approach anywhere else. Does it offer some specific benefits regarding CLIP feature vectors?

Thanks!

**Comment by pbaylies** [comment]
This was something I tried out pre-CLIP which I found worked well for me on feature vectors / embeddings; the thought being that each method might find some different features that might be correlated. Another part of the process I've tried is then processing the resultant features again with PCA as a bottleneck (i.e. going from 512 combined features down to 128 feaures). See here for more: https://gist.github.com/pbaylies/a9358252df1b874d3248071e6fe6dd25

**Comment by njanakiev** [comment]
Thanks, that's indeed interesting! I need to explore that as well. After looking a bit into ICA, it does make some sense in terms of separating features if I understood it correctly which should indeed help with clustering. Have you tried HDBSCAN with or without UMAP/TSNE or any other combinations as well?

I also read that K-Means might be a good initialization for GMM, but not sure if it can be easily applied here.

**Comment by pbaylies** [comment]
I haven't tried HDBBSCAN etc., but certainly you could concatenate features from other methods as well!

The GMM implementation in sklearn already does a lot of nice tricks for you, by default it will initialize with k-means - https://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html
